services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: empleado_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: empleado_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: